### ISSUE TITLE
having trouble running locally

### ISSUE THREAD

**Issue by lpmi-13** [JackieBinya/jacqueline-binya-website#4]
Hi Jacqueline,

I'm trying to run your site locally and having a bit of trouble. I was hoping I could just clone it and run as is with your current submodule setup, but that doesn't seem to be possible.

running `hugo -v server` shows me a whole bunch of errors, and it looks like `index.html` is completely blank. I haven't worked much with git submodules, so it's possible I messed up something obvious. I also tried following the instructions at the bottom of the README, but I wasn't sure which username to substitute in step 4. Should it be my own username?

any help would be much appreciated!

Thanks,
Adam

**Comment by JackieBinya** [comment]
Hello @lpmi-13 
Thanks for taking interest in my project.
Well the instructions I put up there were mainly for me in case I change an OS need to do a fresh install on a new machine.
If want t get started on a blog I suggest you go over the Hugo docs then use the anubis theme.You can customize however way you want.
This a a tutorial I wrote on how I did it: https://jackiebinya.github.io/posts/using-hugo/
If you have any problems do get in touch with me to help you out, but I unfortunately cannot assist you clone my blog with my personal work which includes drafts for new material.
Good luck!

**Comment by lpmi-13** [comment]
ah okay, no worries! I was planning to submit a few PRs to address some lighthouse audit issues, so was hoping I could spin it up locally just to test, but they're fairly minor, so should be able to do it without a local version.
